import { Router } from 'express'; import jwt from 'jsonwebtoken'; import { z } from 'zod'; import { Types } from 'mongoose'; import { OAuth2Client } from 'google-auth-library'; import { User } from '../models/User.js'; import { Workspace } from '../models/Workspace.js'; import { Person } from '../models/Person.js'; import { signAccess, requireAuth, AuthRequest } from '../middleware/auth.js';
const router=Router(), googleInput=z.object({credential:z.string().min(20)}); const googleClient=new OAuth2Client();
const refreshSecret=()=>{const s=process.env.JWT_REFRESH_SECRET;if(!s)throw new Error('JWT_REFRESH_SECRET is required');return s}; const isProd=process.env.NODE_ENV==='production'; const cookie={httpOnly:true,sameSite:(isProd?'none':'lax') as 'none'|'lax',secure:isProd,path:'/api/auth'};
function issue(res:any,user:any){res.cookie('refreshToken',jwt.sign({userId:String(user._id),workspaceId:String(user.workspaceId),tokenVersion:user.tokenVersion},refreshSecret(),{expiresIn:'30d'}),{...cookie,maxAge:30*86400000});return signAccess({userId:String(user._id),workspaceId:String(user.workspaceId),tokenVersion:user.tokenVersion})}
router.post('/google',async(req,res,next)=>{try{const clientId=process.env.GOOGLE_CLIENT_ID;if(!clientId)return res.status(503).json({error:'Google sign-in is not configured'});const {credential}=googleInput.parse(req.body);const ticket=await googleClient.verifyIdToken({idToken:credential,audience:clientId});const profile=ticket.getPayload();if(!profile?.sub||!profile.email||!profile.email_verified)return res.status(401).json({error:'A verified Google email is required'});let user=await User.findOne({googleSubject:profile.sub});if(!user){const workspaceId=new Types.ObjectId(),userId=new Types.ObjectId();[user]=await User.create([{_id:userId,email:profile.email,googleSubject:profile.sub,workspaceId}]);await Workspace.create({_id:workspaceId,ownerUserId:userId,name:`${profile.given_name||'My'}'s financial workspace`});await Person.create({workspaceId,name:profile.name||profile.email.split('@')[0]})}res.json({accessToken:issue(res,user),user:{id:user.id,email:user.email,workspaceId:user.workspaceId}})}catch(err){next(err)}});
router.post('/refresh',async(req,res)=>{try{const token=req.cookies?.refreshToken;if(!token)return res.status(401).json({error:'Session expired'});const p=jwt.verify(token,refreshSecret()) as any;const user=await User.findById(p.userId);if(!user||user.tokenVersion!==p.tokenVersion)return res.status(401).json({error:'Session expired'});res.json({accessToken:issue(res,user)})}catch{res.status(401).json({error:'Session expired'})}});
router.post('/logout',requireAuth,async(req:AuthRequest,res,next)=>{try{await User.updateOne({_id:req.auth!.userId},{$inc:{tokenVersion:1}});res.clearCookie('refreshToken',cookie);res.status(204).end()}catch(err){next(err)}});
router.get('/me',requireAuth,async(req:AuthRequest,res)=>res.json({user:req.auth}));
export default router;
